### ISSUE TITLE
Continuing doesn't preserve the entered description. 

### ISSUE THREAD

**Issue by ejmin** [eManPrague/redmine_tracker#10]
When continuing an entry, the comment is not preserved. After stopping/syncing, the comment is saved, though. 
Closing and opening the app (using the red close button) does temporarily help as it fills the Comment box with correct data. 

Steps to simulate:
1. Start an entry with a description
2. Stop the timer
3. Continue the entry from History (Main timer window must be open)
4. New entry doesn't contain the comment from the previous one
a. (optional) Sync the entry -> Comment is sent to Redmine anyway. 

App version: Version 1.0.0-rc11 (1.0.0-rc11.13)
OS Version: MacOS High Sierra 10.13.3 (17D102)

**Comment by Strnadj** [comment]
resolved in 1.1
