### ISSUE TITLE
User Redmine token is always written in the log when user logs in

### ISSUE THREAD

**Issue by ejmin** [eManPrague/redmine_tracker#12]
The token is always logged and visible for everyone in plaintext. 

Log example:

`[23:02:37:0186] Send FETCH_USER_RESPONSE on {"user":{"id":1,"firstname":"Jon","lastname":"Doe","mail":"jd@example.com","api_key":"a38293c061f6fsomeinvalidkey9ed0bcc2abd71b"},"token":"a38293c061f6fsomeinvalidkey9ed0bcc2abd71b","server":"https://redmine.example.com"}`
...
`[23:02:37:0189] User token securely stored!`

User API token shouldn't probably be accessible as easily as this. 

App version: Version 1.0.0-rc11 (1.0.0-rc11.13)
OS Version: MacOS High Sierra 10.13.3 (17D102)

**Comment by Strnadj** [comment]
Solved in 1.1
