### ISSUE TITLE
Wrong character focus in a description field

### ISSUE THREAD

**Issue by vsouhrada** [eManPrague/redmine_tracker#14]
When typing a text to a description field it works as expected, but when I want to edit some text in desc. field -> then I can type only one char because the focus is set to the end of the text 

How to simulate:
1. Just write text to the description field
2. try to edit text or add some text in a middle or where you want to have it (except the end of text]
v 1.1.0-rc4,
OS : Linux MInt 18.3

**Comment by Strnadj** [comment]
Fixed in rc-5
