### ISSUE TITLE
Sync problem - hours cannot be blank.

### ISSUE THREAD

**Issue by jstorm31** [eManPrague/redmine_tracker#16]
We are having difficulties integrating RedmineTracker with our Redmine. I successfuly log into the app, I can choose project and issue, I can start and stop tracking, but when I try to synchronize time entry with Redmine the response comes back with an error: `Hours cannot be blank`.

Here is a log for an unsuccessful request from RedmineTracker:
```
Started POST "/issues/32172/time_entries?format=json" for 130.211.43.15 at 2019-01-30 12:45:50 +0100
Processing by TimelogController#create as JSON
  Parameters: {"time_entry"=>{"time_from_hours"=>"12:45", "time_to_hours"=>"12:45", "original_hours"=>0, "spent_on"=>"2019-01-30", "comments"=>"Test", "activity_id"=>9}, "issue_id"=>"32172"}
  Current user: jiri.zdvomka@ackee.cz (id=317)
  Rendered common/error_messages.api.rsb (0.2ms)
Completed 422 Unprocessable Entity in 131ms (Views: 0.8ms | ActiveRecord: 90.2ms)
```

And here for a successful request from Redmine web client (removed token and back_url):
```
Started POST "/time_entries" for 130.211.43.15 at 2019-01-30 12:40:01 +0100
Processing by TimelogController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"...", "back_url"=>"...", "issue_id"=>"31800", "time_entry"=>{"issue_id"=>"31800", "spent_on"=>"2019-01-30", "hours"=>"1.01", "comments"=>"Ahoj", "activity_id"=>"9"}, "commit"=>"Create"}
  Current user: tomas.hejatko@ackee.cz (id=359)
```

I guess the problem is in different field naming of `original_hours` in unsuccessful request and `hours` in successful request.

Redmine has been modified as required in Readme here on GitHub.

RedmineTracker version: 1.1.0 (1.1.0.28)
Redmine version: 3.4.7.stable
OS version: macOS Mojave 10.14.2

**Comment by Strnadj** [comment]
Please try to fork and modify
https://github.com/eManPrague/redmine_tracker/blob/master/app/utils/RedmineClient.js#L187
to send `hours` instead of `original_hours`.

**Comment by jstorm31** [comment]
Thank you for reply and localization of the problem. I forked the repo, could build it, but couldn't run the project (there is an error in console). So I changed the file as you proposed and created pull request - https://github.com/eManPrague/redmine_tracker/pull/17. The Travis build in PR failed though.

**Comment by Strnadj** [comment]
@jstorm31 please try last 1.1.1 version

**Comment by jstorm31** [comment]
Great! Thank you.
