### ISSUE TITLE
Project sorting / default project

### ISSUE THREAD

**Issue by subrton** [eManPrague/redmine_tracker#2]
1) Co takhle přidat řazení projektů dle oblíbených v RM? Aby se na prvních místech zobrazily oblíbené projekty, stejně jako je tomu na Dashboardu v Redminu. Zbývající projekty uživatel obvykle nepoužívá.

2) Přidat logiku, aby zůstal předvybrán naposledy použitý projekt. Většinou přes den pracuji na jednom projektu a pouze řeším jiná issue.

**Comment by Strnadj** [comment]
1) v `1.1.0-rc2` vyřešeno projekty jsou řazeny nejdřív favorites pak zbytek abecedně
2) no třeba já dělám na více projektech mne by to štvalo :)
